tables:
  - name: countries
    input_path: '/Workspace/Users/a845678@asb.dtcbtndsie.onmicrosoft.com/assignment/data_storage/1_bronze/src_finance/countries.csv'
    output_path: '/Workspace/Users/a845678@asb.dtcbtndsie.onmicrosoft.com/assignment/data_storage/2_silver/silver_finance/'
    transformations:
      - type: dropDuplicates
    schema:
      name: string 
      alpha-2: string 
      alpha-3: string 
      country-code: bigint
      iso_3166-2: string 
      region: string 
      sub-region: string 
      intermediate-region: string 
      region-code: double 
      sub-region-code: double 
      intermediate-region-code: double 

